/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GhostPay__factory } from "./GhostPay__factory";
export { MockERC20__factory } from "./MockERC20__factory";
