/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GhostPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialBalanceOf"
      | "confidentialBalances"
      | "distributeConfidentialPayroll"
      | "owner"
      | "reclaimToUnderlying"
      | "renounceOwnership"
      | "transferOwnership"
      | "underlying"
      | "wrap"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PayrollDistributed"
      | "SalaryClaimRequested"
      | "UnwrapRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeConfidentialPayroll",
    values: [AddressLike[], BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reclaimToUnderlying",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrap",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeConfidentialPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reclaimToUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollDistributedEvent {
  export type InputTuple = [
    employer: AddressLike,
    employeeCount: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    employer: string,
    employeeCount: bigint,
    totalAmount: bigint
  ];
  export interface OutputObject {
    employer: string;
    employeeCount: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryClaimRequestedEvent {
  export type InputTuple = [employee: AddressLike, unwrapRequestId: BytesLike];
  export type OutputTuple = [employee: string, unwrapRequestId: string];
  export interface OutputObject {
    employee: string;
    unwrapRequestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapRequestedEvent {
  export type InputTuple = [to: AddressLike, unwrapAmount: BytesLike];
  export type OutputTuple = [to: string, unwrapAmount: string];
  export interface OutputObject {
    to: string;
    unwrapAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GhostPay extends BaseContract {
  connect(runner?: ContractRunner | null): GhostPay;
  waitForDeployment(): Promise<this>;

  interface: GhostPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  confidentialBalances: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  distributeConfidentialPayroll: TypedContractMethod<
    [employees: AddressLike[], encryptedAmounts: BytesLike[], arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  reclaimToUnderlying: TypedContractMethod<
    [handle: BytesLike, arg1: BytesLike],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  underlying: TypedContractMethod<[], [string], "view">;

  wrap: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeConfidentialPayroll"
  ): TypedContractMethod<
    [employees: AddressLike[], encryptedAmounts: BytesLike[], arg2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reclaimToUnderlying"
  ): TypedContractMethod<
    [handle: BytesLike, arg1: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "underlying"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wrap"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayrollDistributed"
  ): TypedContractEvent<
    PayrollDistributedEvent.InputTuple,
    PayrollDistributedEvent.OutputTuple,
    PayrollDistributedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryClaimRequested"
  ): TypedContractEvent<
    SalaryClaimRequestedEvent.InputTuple,
    SalaryClaimRequestedEvent.OutputTuple,
    SalaryClaimRequestedEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapRequested"
  ): TypedContractEvent<
    UnwrapRequestedEvent.InputTuple,
    UnwrapRequestedEvent.OutputTuple,
    UnwrapRequestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayrollDistributed(address,uint256,uint256)": TypedContractEvent<
      PayrollDistributedEvent.InputTuple,
      PayrollDistributedEvent.OutputTuple,
      PayrollDistributedEvent.OutputObject
    >;
    PayrollDistributed: TypedContractEvent<
      PayrollDistributedEvent.InputTuple,
      PayrollDistributedEvent.OutputTuple,
      PayrollDistributedEvent.OutputObject
    >;

    "SalaryClaimRequested(address,bytes32)": TypedContractEvent<
      SalaryClaimRequestedEvent.InputTuple,
      SalaryClaimRequestedEvent.OutputTuple,
      SalaryClaimRequestedEvent.OutputObject
    >;
    SalaryClaimRequested: TypedContractEvent<
      SalaryClaimRequestedEvent.InputTuple,
      SalaryClaimRequestedEvent.OutputTuple,
      SalaryClaimRequestedEvent.OutputObject
    >;

    "UnwrapRequested(address,bytes32)": TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
    UnwrapRequested: TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
  };
}
